/**
 * The runnable examples of the developer-experience page. Each `code` string
 * is both the text the page shows and the code the page runs, so an example
 * cannot drift from what it demonstrates.
 */
export interface Example {
  id: string
  title: string
  blurb: string
  code: string
}

export const examples: Example[] = [
  {
    id: 'define',
    title: 'Define a collection',
    blurb:
      'A collection is a typed view of one schema. The Zod schema validates input, applies defaults, transforms values, and gives the collection its type. xdb.js derives an XDB definition from it, so the CLI sees real typed fields.',
    code: [
      "const Post = z.object({",
      "  id: z.string(),",
      "  title: z.string(),",
      "  author: z.string(),                       // the id of a user",
      "  views: z.number().int().default(0),",
      "  tags: z.array(z.string()).default([]),",
      "  createdAt: z.string().transform(v => new Date(v)),",
      "})",
      "",
      "const User = z.object({",
      "  id: z.string(),",
      "  name: z.string(),",
      "  active: z.boolean().default(true),",
      "})",
      "",
      "const posts = createCollection({ uri: 'xdb://app/posts', schema: Post })",
      "const users = createCollection({ uri: 'xdb://app/users', schema: User })",
      "",
      "const db = await createDB({ collections: { posts, users } })",
      "",
      "// The XDB definition xdb.js derived from the Zod schema:",
      "log(posts.def)",
      "",
      "use({ db, posts, users })   // hand these to the other examples",
    ].join('\n'),
  },
  {
    id: 'insert',
    title: 'Insert, and read a typed object back',
    blurb:
      'A mutation reaches memory at once. Persistence happens after. Defaults fill in, and the string transform comes back as a real Date.',
    code: [
      "posts.insert({",
      "  id: 'p-1',",
      "  title: 'Hello',",
      "  author: 'u-1',",
      "  createdAt: '2026-09-13T00:00:00Z',",
      "})",
      "",
      "const post = posts.get('p-1')",
      "",
      "log(post)",
      "log('views came from the default:', post.views)",
      "log('createdAt is a real Date:', post.createdAt instanceof Date, post.createdAt.getUTCFullYear())",
    ].join('\n'),
  },
  {
    id: 'tuples-under',
    title: 'The tuples underneath',
    blurb:
      'The object is a view. Storage is tuples: a path, an attribute, and a typed value. The panel on the right shows every tuple in the store. Read one on its own with an attribute URI.',
    code: [
      "log('one tuple:', db.tuples.get('xdb://app/posts/p-1#title'))",
      "",
      "// The whole record, with the system fields the store stamps.",
      "log(db.records.get('xdb://app/posts/p-1'))",
      "",
      "// Write at the attribute level. The collection sees it immediately.",
      "await db.tuples.put(['app/posts/p-1', 'views', 42])",
      "log('after a tuple write, the object says:', posts.get('p-1').views)",
    ].join('\n'),
  },
  {
    id: 'update',
    title: 'Update through a draft',
    blurb:
      'Mutate a draft. xdb.js diffs the item before and after, so only the attributes that changed reach the driver. A transaction reports the change twice: once as an item, which is what a persistence handler reads, and once as tuples, which is what the store writes.',
    code: [
      "const tx = posts.update('p-1', draft => {",
      "  draft.views += 1",
      "  draft.tags.push('news')",
      "})",
      "",
      "// Item level: type, key, and only the fields that changed.",
      "const m = tx.mutations[0]",
      "log('type:', m.type, 'key:', m.key)",
      "log('changes:', m.changes)",
      "",
      "// Tuple level: what the store actually writes.",
      "log('tuple writes:', tx.writes.map(w => w.op + ' ' + (w.tuples ?? []).map(t => t.attr).join(',')))",
      "",
      "await tx.isPersisted.promise",
      "log('after persist:', posts.get('p-1'))",
    ].join('\n'),
  },
  {
    id: 'live',
    title: 'A live query with a join',
    blurb:
      'The builder joins collections on a shared value. The query returns rows now, and again after every commit that touches what it read. Run this, then run the next example and watch the rows change on their own.',
    code: [
      "users.insert([",
      "  { id: 'u-1', name: 'Ada' },",
      "  { id: 'u-2', name: 'Grace' },",
      "])",
      "posts.insert([",
      "  { id: 'p-2', title: 'Quiet',  author: 'u-1', views: 3,   createdAt: '2026-09-02T00:00:00Z' },",
      "  { id: 'p-3', title: 'Third',  author: 'u-2', views: 900, createdAt: '2026-09-03T00:00:00Z' },",
      "])",
      "",
      "const popular = db.live(q =>",
      "  q.from({ post: posts })",
      "   .join({ user: users }, ({ post, user }) => eq(post.author, user.id))",
      "   .where(({ post, user }) => and(gt(post.views, 100), eq(user.active, true)))",
      "   .select(({ post, user }) => ({ id: post.id, title: post.title, by: user.name }))",
      "   .orderBy(({ post }) => post.views, 'desc')",
      ")",
      "",
      "log('rows now:', popular.toArray())",
      "",
      "// Keep it on screen. The right panel re-renders when it emits.",
      "watchLive('popular', popular)",
    ].join('\n'),
  },
  {
    id: 'reactive',
    title: 'Mutate, and the query re-runs itself',
    blurb:
      'Nothing here mentions the query. The store compares each commit against what every live query read, and re-runs only the queries that overlap.',
    code: [
      "// p-2 has 3 views, so it is outside the query. Push it over the line.",
      "await posts.update('p-2', d => { d.views = 500 }).isPersisted.promise",
      "log('p-2 now has 500 views. The popular panel gained a row.')",
      "",
      "// This write touches an attribute the query never read, so it does not re-run.",
      "await posts.update('p-2', d => { d.tags = ['quiet'] }).isPersisted.promise",
      "log('a tags write does not re-run the query. The panel did not change.')",
    ].join('\n'),
  },
  {
    id: 'tx',
    title: 'One transaction, one commit',
    blurb:
      'A transaction groups writes across collections. The driver receives one batch, and a live query sees one change rather than several.',
    code: [
      "const tx = createTransaction({ store: db.store })",
      "",
      "tx.mutate(() => {",
      "  posts.update('p-1', d => { d.views += 10 })",
      "  users.update('u-1', d => { d.name = 'Ada Lovelace' })",
      "})",
      "",
      "log('buffered, not applied yet:', tx.mutations.length, 'mutations')",
      "await tx.commit()",
      "",
      "log(posts.get('p-1').views, users.get('u-1').name)",
    ].join('\n'),
  },
  {
    id: 'aggregates',
    title: 'Group and aggregate',
    blurb:
      'A where clause builds an expression tree, not a per-row predicate, so the compiler can read it. That is also what makes groupBy and the aggregates work: count, sum, avg, min and max fold over each group.',
    code: [
      "const byAuthor = db.live(q =>",
      "  q.from({ post: posts })",
      "   .groupBy(({ post }) => post.author)",
      "   .select(({ post }) => ({",
      "     author: post.author,",
      "     posts:  count(),",
      "     views:  sum(post.views),",
      "     best:   max(post.views),",
      "   }))",
      "   .having(() => gt(count(), 0))",
      "   .orderBy(({ post }) => sum(post.views), 'desc')",
      ")",
      "",
      "log(byAuthor.toArray())",
      "watchLive('byAuthor', byAuthor)",
    ].join('\n'),
  },
  {
    id: 'joins',
    title: 'Four join kinds',
    blurb:
      'An eq between two fields is the join: the compiler unifies their variables instead of filtering rows. A left join keeps a post whose author is missing. A right join keeps an author with no posts.',
    code: [
      "// An author who wrote nothing, and a post pointing at nobody.",
      "users.insert({ id: 'u-idle', name: 'Idle Ian' })",
      "posts.insert({ id: 'p-orphan', title: 'Orphan', author: 'u-gone',",
      "  createdAt: '2026-09-09T00:00:00Z' })",
      "",
      "const on = ({ post, user }) => eq(post.author, user.id)",
      "const pick = ({ post, user }) => ({ title: post.title, by: user.name })",
      "",
      "log('inner:', query().from({ post: posts }).innerJoin({ user: users }, on).select(pick).run(db.store.index))",
      "log('left: ', query().from({ post: posts }).leftJoin({ user: users }, on).select(pick).run(db.store.index))",
      "log('right:', query().from({ post: posts }).rightJoin({ user: users }, on).select(pick).run(db.store.index))",
      "log('full: ', query().from({ post: posts }).fullJoin({ user: users }, on).select(pick).run(db.store.index))",
    ].join('\n'),
  },
  {
    id: 'subquery',
    title: 'A live query is a collection',
    blurb:
      'createLiveQueryCollection returns a collection, so its result is a source for another query. The rows are materialized as tuples under the _live namespace, which is why a subquery needs nothing new from the engine. Watch the right panel.',
    code: [
      "const popular = createLiveQueryCollection({",
      "  id: 'popular',",
      "  query: q => q.from({ post: posts })",
      "               .where(({ post }) => gt(post.views, 100))",
      "               .select(({ post }) => ({ id: post.id, title: post.title, author: post.author })),",
      "})",
      "popular.bind(db.store)",
      "",
      "log('popular rows:', popular.toArray())",
      "",
      "// Now query the query.",
      "const perAuthor = query()",
      "  .from({ p: popular })",
      "  .groupBy(({ p }) => p.author)",
      "  .select(({ p }) => ({ author: p.author, n: count() }))",
      "  .run(db.store.index)",
      "",
      "log('grouped from the subquery:', perAuthor)",
      "",
      "// Keep it on screen. Editing a post's views moves rows in and out.",
      "watchLive('popular (a collection)', popular)",
    ].join('\n'),
  },
  {
    id: 'fn',
    title: 'The fn escape hatch',
    blurb:
      'When a condition cannot be expressed with the expression functions, fn.where takes a plain JavaScript predicate over the whole row. It runs per row, so it uses no index and the compiler cannot reorder around it. TanStack DB draws the same line.',
    code: [
      "const oddTitles = query()",
      "  .from({ post: posts })",
      "  .fn.where(row => row.post.title.length % 2 === 1)",
      "  .select(({ post }) => ({ title: post.title }))",
      "  .run(db.store.index)",
      "",
      "log('titles of odd length:', oddTitles)",
      "",
      "// fn.select shapes the output however you like, after limit.",
      "const labels = query()",
      "  .from({ post: posts })",
      "  .select(({ post }) => ({ t: post.title, v: post.views }))",
      "  .orderBy(({ post }) => post.views, 'desc')",
      "  .limit(3)",
      "  .fn.select(row => row.t + ' (' + row.v + ')')",
      "  .run(db.store.index)",
      "",
      "log(labels)",
    ].join('\n'),
  },
  {
    id: 'handlers',
    title: 'Persist with onInsert and friends',
    blurb:
      'A handler receives the transaction, with item-level mutations: type, key, original, modified and changes. The change is already in memory when the handler runs. If the handler rejects, the change is reverted.',
    code: [
      "const sent = []",
      "const notes = createCollection({",
      "  uri: 'xdb://app/notes',",
      "  onInsert: async ({ transaction }) => {",
      "    sent.push(transaction.mutations.map(m => ({ type: m.type, key: m.key, body: m.modified })))",
      "  },",
      "  onUpdate: async ({ transaction }) => {",
      "    const m = transaction.mutations[0]",
      "    log('changed fields only:', m.changes)",
      "    throw new Error('the server refused this one')",
      "  },",
      "})",
      "notes.bind(db.store)",
      "",
      "await notes.insert({ id: 'n-1', text: 'first', pinned: false }).isPersisted.promise",
      "log('the handler saw:', sent)",
      "",
      "const tx = notes.update('n-1', d => { d.pinned = true })",
      "log('in memory at once:', notes.get('n-1').pinned)",
      "try { await tx.isPersisted.promise } catch (err) { log('rejected:', err.message) }",
      "log('reverted:', notes.get('n-1').pinned)",
    ].join('\n'),
  },
  {
    id: 'optimistic',
    title: 'An optimistic action',
    blurb:
      'createOptimisticAction pairs an instant local change with the request that confirms it. The rollback is automatic.',
    code: [
      "const bump = createOptimisticAction({",
      "  onMutate: id => posts.update(id, d => { d.views += 1000 }),",
      "  mutationFn: async () => { throw new Error('network down') },",
      "})",
      "",
      "const before = posts.get('p-1').views",
      "const tx = bump('p-1')",
      "log('instantly:', posts.get('p-1').views, '(was', before + ')')",
      "",
      "try { await tx.isPersisted.promise } catch (err) { log('failed:', err.message) }",
      "log('rolled back to:', posts.get('p-1').views)",
      "log('transaction state:', tx.state)",
    ].join('\n'),
  },
  {
    id: 'collection-api',
    title: 'The collection surface',
    blurb:
      'A collection is a keyed view: state is a Map, and entries, values and keys are iterators. status and preload cover loading, and subscribeChanges reports item-level changes rather than whole lists.',
    code: [
      "log('size:', posts.size, 'status:', posts.status, 'ready:', posts.isReady())",
      "log('keys:', [...posts.keys()])",
      "log('one item from state:', posts.state.get('p-1'))",
      "",
      "const stop = posts.subscribeChanges(changes => {",
      "  log('change:', changes.map(c => c.type + ' ' + c.key).join(', '))",
      "}, { includeInitialState: true })",
      "",
      "posts.insert({ id: 'p-live', title: 'Watched', author: 'u-1',",
      "  createdAt: '2026-09-10T00:00:00Z' })",
      "",
      "// Let the change batch flush, then stop listening.",
      "await new Promise(r => setTimeout(r, 0))",
      "stop()",
    ].join('\n'),
  },
  {
    id: 'patterns',
    title: 'The tuple layer: pattern queries',
    blurb:
      'This is the engine the builder compiles to. A variable starts with a question mark. A variable in two patterns joins them. Use it for tools, migrations, and data with no schema.',
    code: [
      "const rows = db.query({",
      "  find: ['?title', '?name', '?views'],",
      "  where: [",
      "    ['app/posts/?p', 'author', '?u'],     // ?p binds to the post id, ?u to the user id",
      "    ['app/users/?u', 'name',   '?name'],  // ?u appears again, so this is the join",
      "    ['app/posts/?p', 'title',  '?title'],",
      "    ['app/posts/?p', 'views',  '?views'],",
      "    '?views > 100',                        // a predicate over bound variables",
      "  ],",
      "})",
      "",
      "log(rows)",
    ].join('\n'),
  },
  {
    id: 'filters',
    title: 'Lists and predicates',
    blurb:
      'A list takes a predicate. There is no filter language, because JavaScript already has one. Paging returns the total count and the next offset.',
    code: [
      "log(db.records.list('xdb://app/posts', { filter: r => r.views >= 100 }))",
      "",
      "log(db.records.list('xdb://app/posts', {",
      "  filter: r => r.title.startsWith('Q') || r.views > 500,",
      "  limit: 1,",
      "}))",
    ].join('\n'),
  },
  {
    id: 'errors',
    title: 'Errors carry a code',
    blurb:
      'Every failure is an XDBError with a code from the XDB catalog. A schema failure names the fields that broke.',
    code: [
      "// A missing required field.",
      "try {",
      "  posts.insert({ id: 'bad', author: 'u-1', createdAt: '2026-01-01T00:00:00Z' })",
      "} catch (err) {",
      "  log(err.code, err.issues)",
      "}",
      "",
      "// A duplicate key.",
      "try {",
      "  posts.insert({ id: 'p-1', title: 'again', author: 'u-1', createdAt: '2026-01-01T00:00:00Z' })",
      "} catch (err) {",
      "  log(err.code, err.message)",
      "}",
      "",
      "// A stale version precondition.",
      "const stale = db.store.get('app/posts/p-1', '_version').value",
      "await db.store.apply([{ path: 'app/posts/p-1', op: 'patch', tuples: [{ path: 'app/posts/p-1', attr: 'title', value: 'B' }] }])",
      "try {",
      "  await db.store.apply([{ path: 'app/posts/p-1', op: 'patch', version: stale,",
      "    tuples: [{ path: 'app/posts/p-1', attr: 'title', value: 'C' }] }])",
      "} catch (err) {",
      "  log(err.code, '- the title is still', posts.get('p-1').title)",
      "}",
    ].join('\n'),
  },
  {
    id: 'schemaless',
    title: 'No schema, no problem',
    blurb:
      'A collection without a schema runs in dynamic mode. The store infers each type from the value and adds the field to the definition.',
    code: [
      "const events = createCollection({ uri: 'xdb://app/events' })",
      "events.bind(db.store)",
      "",
      "events.insert({ id: 'e-1', kind: 'view', at: new Date(), weight: 1.5, ok: true })",
      "",
      "log(events.get('e-1'))",
      "log('the definition it inferred:', db.store.def('app/events'))",
    ].join('\n'),
  },
]
